### ISSUE TITLE
Question about picture and model

### ISSUE THREAD

**Issue by Z-Xiong** [mxahan/tflite_implementation#1]
Thanks for your work, I have two questions for you. What rppg model are you using? Is the image used for inferencing compressed or original?

**Comment by mxahan** [comment]
Thank you for your interest.

i)  We are using the CamSense model. 

ii) I am a bit confused about the second question. The first image demonstrates the inference motivation. The second image refers to the overall approach to developing the Rhythmedge model. The final image depicts our system overview during inference time. Please refer to the paper for the details.

**Comment by Z-Xiong** [comment]
Sorry, I was not very clear about the second question. I want to ask whether your network input image is compressed or original yuv image.

**Comment by mxahan** [comment]
Oh, the Network takes 40 consecutive frames of resized 100x100 green channel. In short, the input is  100x100x40 (~1.3 seconds of video). We didn't perform any compression on the frames. However, we resize it to 100x100 and normalize it. 

Once we read the video via the OpenCV video reader, we solely work on the python data processing. If  I remember correctly, the OpenCV could read the raw YUV video frames. 

Hope that solves the confusion. Please refer to the CamSense paper for detail on the input data processing.

**Comment by Z-Xiong** [comment]
Thank you very much for your reply.
